version: 2
jobs:
  build:
    docker:
      - image: nexela/factorio-lua-env
    working_directory: /root/mod
    steps:
      - checkout
      - run: curl -s -o .luacheckrc https://raw.githubusercontent.com/Nexela/Factorio-luacheckrc/master/.luacheckrc
      - run: luacheck .
      - run: make quick
      - run: make check
      - store_artifacts:
          path: .build/artifacts
          destination: /files

  release:
    docker:
      - image: nexela/factorio-lua-env
    working_directory: /root/mod
    steps:
      - checkout
      - run:
          name: Build Project
          command: echo Building Project

      - run: curl -s -o .luacheckrc https://raw.githubusercontent.com/Nexela/Factorio-luacheckrc/master/.luacheckrc
      - run: luacheck .
      - run: make quick
      - run: make check
      - store_artifacts:
          path: .build/artifacts
          destination: /files

      - run:
          name: Export Vars
          command: |
            echo 'export NAME=$(jq -r '.name' info.json)' >> $BASH_ENV
            echo 'export VERSION=$(jq -r '.version' info.json)' >> $BASH_ENV
            echo 'FILEPATH="${CIRCLE_WORKING_DIRECTORY}/.build/artifacts/${NAME}_${VERSION}.zip"' >> $BASH_ENV
            echo 'FILESIZE=$(stat --printf="%s" "${FILEPATH}")' >> $BASH_ENV

      - run:
          name: Check for changelog entry
          command: |
            grep "Version: ${VERSION}" changelog.txt

      - run:
          name: Upload Release
          command: ${CIRCLE_WORKING_DIRECTORY}/.circleci/release.sh

      - run:
          name: Tag Project
          command: |
            git tag v${VERSION}
            git push --tags

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - /feature-.*/
                - release
      - release:
          context: FactorioUpload
          # requires:
          #   - build
          filters:
            branches:
              only: release
